---
# vars file for containerized-hmi
docker_hmi_packages:
    - apt-transport-https
    - ca-certificates
    - curl 
    - gnupg-agent
    - software-properties-common
    - docker
    - docker-compose
